dbt_project:
   outputs:
      dev:
         type: bigquery
         threads: 3
         method: service-account
         project: "{{env_var('GCP_PROJECT_ID')}}"
         dataset : dw
         keyfile : "{{env_var('GCP_JSON_KEYFILE_PATH')}}"
         timeout_seconds: 300
   target: dev