version: 2

models:
  - name: fact_orders
    description: "Join of orders, order_details, and products"
    columns:
      - name: order_id
        tests: [not_null]
      - name: customer_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: price
        tests: [not_null]
      - name: quantity
        tests: [not_null]
      - name: total_price
        tests: [not_null]

  - name: fact_customer_orders
    description: "Total spend per customer"
    columns:
      - name: customer_name
        tests: [not_null]
      - name: total_amount_spent
        tests: [not_null]
