version: 2

models:
  - name: fact_orders
    description: "Join of orders, order_details, and products with item details aggregated into an array."
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: items 
        tests:
          - not_null 

  - name: customer_total_spent
    description: "Total spend per customer"
    columns:
      - name: customer_name
        tests: [not_null]
      - name: total_amount_spent
        tests:
          - not_null
