version: 2

sources:
  - name: raw
    schema: dw_raw
    database: "{{ target.project }}"
    tables:
      - name: customers
        columns:
          - name: customer_id
            tests: [not_null]
          - name: updated_at
            tests: [not_null]

      - name: orders
        columns:
          - name: order_id
            tests: [not_null]
          - name: updated_at
            tests: [not_null]

      - name: order_details
        columns:
          - name: order_id
            tests: [not_null]
          - name: product_id
            tests: [not_null]
          - name: updated_at
            tests: [not_null]

      - name: products
        columns:
          - name: product_id
            tests: [not_null]
