version: 2

sources:
  - name: raw
    schema: dw
    database: "{{ target.project }}"
    tables:
      - name: customers_raw
        columns:
          - name: customer_id
            tests: [not_null]
          - name: updated_at
            tests: [not_null]

      - name: orders_raw
        columns:
          - name: order_id
            tests: [not_null]
          - name: updated_at
            tests: [not_null]

      - name: order_details_raw
        columns:
          - name: order_id
            tests: [not_null]
          - name: product_id
            tests: [not_null]
          - name: updated_at
            tests: [not_null]

      - name: products_raw
        columns:
          - name: product_id
            tests: [not_null]
